const personagens = [
    "Marcos (Discípulo",
    "Abel (Filho de Adão",
    "Abraão (Patriarca",
    "Adão (Primeiro homem",
    "Ana (Mãe de Samuel",
    "Moisés (Mar vermelho",
    "Benjamim (Filho caçula de Jacó",
    "Caim (Matou o irmão",
    "Noé (Arca",
    "Dalila (Traiu Sansão",
    "Daniel (Profeta na Babilônia",
    "Davi (Rei de Israel",
    "Elias (Carruagem de fogo",
    "Eliseu (Fez o machado flutuar",
    "Esaú (Teve a primogenitura roubada",
    "Ester (Foi rainha na Pérsia",
    "Eva (Primeira mulher",
    "Golias (Gigante",
    "Herodes (Rei da Judeia",
    "Isaque (Filho de Abraão",
    "Isabel (Mãe de João Batista",
    "Isaías (Profeta",
    "Ismael (Meio irmão de Isaque",
    "Jacó (Israel",
    "Jeremias (Profeta",
    "André (Irmão de Pedro",
    "Jezabel (Rainha má",
    "Jonas (Baleia",
    "Paulo (Apóstolo dos gentios",
    "Pedro (Irmão de André",
    "Raquel (Esposa de Jacó",
    "Rebeca (Esposa de Isaque",
    "Rute (Sogra de Noemi",
    "Salomão (Constuiu o templo",
    "Samuel (Ungiu Davi",
    "Sansão (Forte",
    "Sara (Mulher de Abraão",
    "Saul (Primeiro Rei",
    "Tiago (Discípulo",
    "Timóteo (Discípulo de Paulo",
    "Tomé (Ver pra crer",
    "Josué (Sucedeu Moisés",
    "José (Príncipe do Egito",
    "João (Apocalipse",
    "Judas Tadeu(Apóstolo irmão de Tiago",
    "Jó (Paciência",
    "Jônatas (Amigo de Davi",
    "Labão (Sogro de Jacó",
    "Lia (Primeira mulher de jacó",
    "Lucas (Evangelho",
    "Lázaro (Ressuscitou",
    "Maria (irmã de Lázaro",
    "Marta (irmã de Lázaro",
    "Mateus (primeiro evangelho",			
    "Zaqueu (Árvore"
];